ServerEvents.recipes((event) => {
  const gtr = event.recipes.gtceu;


  gtr.assembler("gtceu:dimensional_rift_extractor")
    .itemInputs("gtceu:lv_miner",
                "gtceu:mv_miner",
                "gtceu:hv_miner",
                "6x gtceu:hv_field_generator",
                "4x gtceu:hv_world_accelerator",
                "4x #gtceu:circuits/ev",
                "8x gtceu:casing_stainless_clean",
                "4x gtceu:titanium_gear")
    .inputFluids("gtceu:soldering_alloy 1440")
    .itemOutputs("gtceu:dimensional_rift_extractor")
    .EUt(GTValues.VA[GTValues.HV])
    .duration(800);

  gtr.dimensional_rift_extractor('dimensional_rift_extractor')
    .inputFluids('minecraft:lava 1152', 'gtceu:naquad_alloy 1152')
    .outputFluids('minecraft:water 3000')
    .duration(1800)
    .EUt(131072);

  gtr.assembly_line('reborn_dimensional_rift_extractor')
    .itemInputs('4x #gtceu:circuits/zpm', '8x kubejs:plasma_resistant')
    .inputFluids('gtceu:soldering_alloy 1152', 'gtceu:niobium_titanium 1152')
    .itemOutputs('gtceu:reborn_dimensional_rift_extractor')
    .duration(75)
    .EUt(29723)
    .stationResearch(b => b.researchStack(Item.of('minecraft:dirt')).EUt(30720).CWUt(16, 32000));

    gtr.dimensional_rift_extractor("bentonite_ore_overworld")
    .notConsumable("1x gtceu:raw_bentonite")
    .itemOutputs("1x gtceu:bentonite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("magnetite_ore_overworld")
    .notConsumable("1x gtceu:raw_magnetite")
    .itemOutputs("1x gtceu:magnetite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("olivine_ore_overworld")
    .notConsumable("1x gtceu:raw_olivine")
    .itemOutputs("1x gtceu:olivine_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("glauconite_sand_ore_overworld")
    .notConsumable("1x gtceu:raw_glauconite_sand")
    .itemOutputs("1x gtceu:glauconite_sand_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("almandine_ore_overworld")
    .notConsumable("1x gtceu:raw_almandine")
    .itemOutputs("3x gtceu:almandine_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("pyrope_ore_overworld")
    .notConsumable("1x gtceu:raw_pyrope")
    .itemOutputs("2x gtceu:pyrope_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("sapphire_ore_overworld")
    .notConsumable("1x gtceu:raw_sapphire")
    .itemOutputs("1x gtceu:sapphire_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("green_sapphire_ore_overworld")
    .notConsumable("1x gtceu:raw_green_sapphire")
    .itemOutputs("1x gtceu:green_sapphire_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("goethite_ore_overworld")
    .notConsumable("1x gtceu:raw_goethite")
    .itemOutputs("1x gtceu:goethite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("yellow_limonite_ore_overworld")
    .notConsumable("1x gtceu:raw_yellow_limonite")
    .itemOutputs("4x gtceu:yellow_limonite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("hematite_ore_overworld")
    .notConsumable("1x gtceu:raw_hematite")
    .itemOutputs("4x gtceu:hematite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("malachite_ore_overworld")
    .notConsumable("1x gtceu:raw_malachite")
    .itemOutputs("2x gtceu:malachite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("soapstone_ore_overworld")
    .notConsumable("1x gtceu:raw_soapstone")
    .itemOutputs("2x gtceu:soapstone_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("talc_ore_overworld")
    .notConsumable("1x gtceu:raw_talc")
    .itemOutputs("1x gtceu:talc_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("glauconite_sand_ore_overworld_2") // Added a suffix to avoid duplicate name
    .notConsumable("1x gtceu:raw_glauconite_sand")
    .itemOutputs("1x gtceu:glauconite_sand_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("pentlandite_ore_overworld")
    .notConsumable("1x gtceu:raw_pentlandite")
    .itemOutputs("1x gtceu:pentlandite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("grossular_ore_overworld")
    .notConsumable("1x gtceu:raw_grossular")
    .itemOutputs("1x gtceu:grossular_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("spessartine_ore_overworld")
    .notConsumable("1x gtceu:raw_spessartine")
    .itemOutputs("1x gtceu:spessartine_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("pyrolusite_ore_overworld")
    .notConsumable("1x gtceu:raw_pyrolusite")
    .itemOutputs("1x gtceu:pyrolusite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("tantalite_ore_overworld")
    .notConsumable("1x gtceu:raw_tantalite")
    .itemOutputs("1x gtceu:tantalite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("chalcopyrite_ore_overworld")
    .notConsumable("1x gtceu:raw_chalcopyrite")
    .itemOutputs("4x gtceu:chalcopyrite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("zeolite_ore_overworld")
    .notConsumable("1x gtceu:raw_zeolite")
    .itemOutputs("1x gtceu:zeolite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("cassiterite_ore_overworld")
    .notConsumable("1x gtceu:raw_cassiterite")
    .itemOutputs("1x gtceu:cassiterite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("realgar_ore_overworld")
    .notConsumable("1x gtceu:raw_realgar")
    .itemOutputs("1x gtceu:realgar_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("coal_ore_overworld")
    .notConsumable("1x gtceu:raw_coal")
    .itemOutputs("4x gtceu:coal_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("iron_ore_overworld")
    .notConsumable("1x minecraft:raw_iron")
    .itemOutputs("2x minecraft:iron_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("pyrite_ore_overworld")
    .notConsumable("1x gtceu:raw_pyrite")
    .itemOutputs("2x gtceu:pyrite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("copper_ore_overworld")
    .notConsumable("1x minecraft:raw_copper")
    .itemOutputs("2x minecraft:copper_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("vanadium_magnetite_ore_overworld")
    .notConsumable("1x gtceu:raw_vanadium_magnetite")
    .itemOutputs("2x gtceu:vanadium_magnetite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("gold_ore_overworld")
    .notConsumable("1x minecraft:raw_gold")
    .itemOutputs("1x minecraft:gold_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("lazurite_ore_overworld")
    .notConsumable("1x gtceu:raw_lazurite")
    .itemOutputs("2x gtceu:lazurite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("sodalite_ore_overworld")
    .notConsumable("1x gtceu:raw_sodalite")
    .itemOutputs("1x gtceu:sodalite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("lapis_ore_overworld")
    .notConsumable("1x gtceu:raw_lapis")
    .itemOutputs("1x gtceu:lapis_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("calcite_ore_overworld")
    .notConsumable("1x gtceu:raw_calcite")
    .itemOutputs("1x gtceu:calcite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("galena_ore_overworld")
    .notConsumable("1x gtceu:raw_galena")
    .itemOutputs("2x gtceu:galena_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("silver_ore_overworld")
    .notConsumable("1x gtceu:raw_silver")
    .itemOutputs("1x gtceu:silver_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("lead_ore_overworld")
    .notConsumable("1x gtceu:raw_lead")
    .itemOutputs("1x gtceu:lead_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("kyanite_ore_overworld")
    .notConsumable("1x gtceu:raw_kyanite")
    .itemOutputs("1x gtceu:kyanite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("mica_ore_overworld")
    .notConsumable("1x gtceu:raw_mica")
    .itemOutputs("1x gtceu:mica_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("bauxite_ore_overworld")
    .notConsumable("1x gtceu:raw_bauxite")
    .itemOutputs("1x gtceu:bauxite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("pollucite_ore_overworld")
    .notConsumable("1x gtceu:raw_pollucite")
    .itemOutputs("1x gtceu:pollucite_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld");
gtr.dimensional_rift_extractor("tin_ore_overworld")
    .notConsumable("1x gtceu:raw_tin")
    .itemOutputs("5x gtceu:tin_ore")
    .duration(75)
    .EUt(512)
    .dimension("overworld")
    gtr.dimensional_rift_extractor("cassiterite_ore_overworld_2") // Added a suffix
        .notConsumable("1x gtceu:raw_cassiterite")
        .itemOutputs("3x gtceu:cassiterite_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("red_garnet_ore_overworld")
        .notConsumable("1x gtceu:raw_red_garnet")
        .itemOutputs("2x gtceu:red_garnet_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("yellow_garnet_ore_overworld")
        .notConsumable("1x gtceu:raw_yellow_garnet")
        .itemOutputs("1x gtceu:yellow_garnet_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("amethyst_ore_overworld")
        .notConsumable("1x gtceu:raw_amethyst")
        .itemOutputs("1x gtceu:amethyst_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("opal_ore_overworld")
        .notConsumable("1x gtceu:raw_opal")
        .itemOutputs("1x gtceu:opal_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("basaltic_mineral_sand_ore_overworld")
        .notConsumable("1x gtceu:raw_basaltic_mineral_sand")
        .itemOutputs("4x gtceu:basaltic_mineral_sand_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("granitic_mineral_sand_ore_overworld")
        .notConsumable("1x gtceu:raw_granitic_mineral_sand")
        .itemOutputs("2x gtceu:granitic_mineral_sand_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("fullers_earth_ore_overworld")
        .notConsumable("1x gtceu:raw_fullers_earth")
        .itemOutputs("2x gtceu:fullers_earth_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("gypsum_ore_overworld")
        .notConsumable("1x gtceu:raw_gypsum")
        .itemOutputs("1x gtceu:gypsum_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("rock_salt_ore_overworld")
        .notConsumable("1x gtceu:raw_rock_salt")
        .itemOutputs("2x gtceu:rock_salt_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("salt_ore_overworld")
        .notConsumable("1x gtceu:raw_salt")
        .itemOutputs("1x gtceu:salt_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("lepidolite_ore_overworld")
        .notConsumable("1x gtceu:raw_lepidolite")
        .itemOutputs("1x gtceu:lepidolite_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("spodumene_ore_overworld")
        .notConsumable("1x gtceu:raw_spodumene")
        .itemOutputs("1x gtceu:spodumene_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("redstone_ore_overworld")
        .notConsumable("1x gtceu:raw_redstone")
        .itemOutputs("3x gtceu:redstone_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("ruby_ore_overworld")
        .notConsumable("1x gtceu:raw_ruby")
        .itemOutputs("2x gtceu:ruby_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("cinnabar_ore_overworld")
        .notConsumable("1x gtceu:raw_cinnabar")
        .itemOutputs("1x gtceu:cinnabar_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("apatite_ore_overworld")
        .notConsumable("1x gtceu:raw_apatite")
        .itemOutputs("2x gtceu:apatite_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("tricalcium_phosphate_ore_overworld")
        .notConsumable("1x gtceu:raw_tricalcium_phosphate")
        .itemOutputs("1x gtceu:tricalcium_phosphate_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("pyrochlore_ore_overworld")
        .notConsumable("1x gtceu:raw_pyrochlore")
        .itemOutputs("1x gtceu:pyrochlore_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("cassiterite_sand_ore_overworld")
        .notConsumable("1x gtceu:raw_cassiterite_sand")
        .itemOutputs("4x gtceu:cassiterite_sand_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("garnet_sand_ore_overworld")
        .notConsumable("1x gtceu:raw_garnet_sand")
        .itemOutputs("2x gtceu:garnet_sand_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("asbestos_ore_overworld")
        .notConsumable("1x gtceu:raw_asbestos")
        .itemOutputs("2x gtceu:asbestos_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("diatomite_ore_overworld")
        .notConsumable("1x gtceu:raw_diatomite")
        .itemOutputs("1x gtceu:diatomite_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("oilsands_ore_overworld")
        .notConsumable("1x gtceu:raw_oilsands")
        .itemOutputs("4x gtceu:oilsands_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("graphite_ore_overworld")
        .notConsumable("1x gtceu:raw_graphite")
        .itemOutputs("2x gtceu:graphite_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("diamond_ore_overworld")
        .notConsumable("1x gtceu:raw_diamond")
        .itemOutputs("1x gtceu:diamond_ore")
        .duration(75)
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("garnierite_ore_overworld")
        .notConsumable("1x gtceu:raw_garnierite")
        .itemOutputs("2x gtceu:garnierite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("nickel_ore_overworld")
        .notConsumable("1x gtceu:raw_nickel")
        .itemOutputs("1x gtceu:nickel_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("cobaltite_ore_overworld")
        .notConsumable("1x gtceu:raw_cobaltite")
        .itemOutputs("1x gtceu:cobaltite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("overworld");
    gtr.dimensional_rift_extractor("pentlandite_ore_overworld_2") // Added a suffix
        .notConsumable("1x gtceu:raw_pentlandite")
        .itemOutputs("1x gtceu:pentlandite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .inputFluids("gtceu:drilling_fluid 500")
        .dimension("overworld");

    // Nether Recipes
    gtr.dimensional_rift_extractor("tetrahedrite_ore_nether")
        .notConsumable("1x gtceu:raw_tetrahedrite")
        .itemOutputs("4x gtceu:tetrahedrite_ore")
        .duration(75)
        .EUt(512)
        .inputFluids("gtceu:drilling_fluid 500")
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("copper_ore_nether")
        .notConsumable("1x minecraft:raw_copper")
        .itemOutputs("2x minecraft:copper_ore")
        .duration(75)
        .EUt(512)
        .inputFluids("gtceu:drilling_fluid 500")
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("stibnite_ore_nether")
        .notConsumable("1x gtceu:raw_stibnite")
        .itemOutputs("1x gtceu:stibnite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("bastnasite_ore_nether")
        .notConsumable("1x gtceu:raw_bastnasite")
        .itemOutputs("1x gtceu:bastnasite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("molybdenum_ore_nether")
        .notConsumable("1x gtceu:raw_molybdenum")
        .itemOutputs("1x gtceu:molybdenum_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("neodymium_ore_nether")
        .notConsumable("1x gtceu:raw_neodymium")
        .itemOutputs("1x gtceu:neodymium_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("monazite_ore_nether")
        .notConsumable("1x gtceu:raw_monazite")
        .itemOutputs("1x gtceu:monazite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("redstone_ore_nether")
        .notConsumable("1x gtceu:raw_redstone")
        .itemOutputs("3x gtceu:redstone_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("ruby_ore_nether")
        .notConsumable("1x gtceu:raw_ruby")
        .itemOutputs("2x gtceu:ruby_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("cinnabar_ore_nether")
        .notConsumable("1x gtceu:raw_cinnabar")
        .itemOutputs("1x gtceu:cinnabar_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("saltpeter_ore_nether")
        .notConsumable("1x gtceu:raw_saltpeter")
        .itemOutputs("2x gtceu:saltpeter_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("diatomite_ore_nether")
        .notConsumable("1x gtceu:raw_diatomite")
        .itemOutputs("1x gtceu:diatomite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("electrotine_ore_nether")
        .notConsumable("1x gtceu:raw_electrotine")
        .itemOutputs("1x gtceu:electrotine_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("alunite_ore_nether")
        .notConsumable("1x gtceu:raw_alunite")
        .itemOutputs("1x gtceu:alunite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("beryllium_ore_nether")
        .notConsumable("1x gtceu:raw_beryllium")
        .itemOutputs("1x gtceu:beryllium_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
        gtr.dimensional_rift_extractor("emerald_ore_nether")
        .notConsumable("1x gtceu:raw_emerald")
        .itemOutputs("2x gtceu:emerald_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("grossular_ore_nether")
        .notConsumable("1x gtceu:raw_grossular")
        .itemOutputs("1x gtceu:grossular_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("pyrolusite_ore_nether")
        .notConsumable("1x gtceu:raw_pyrolusite")
        .itemOutputs("1x gtceu:pyrolusite_ore")
        .inputFluids("gtceu:drilling_fluid 500")
        .duration(75)
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("tantalite_ore_nether")
        .notConsumable("1x gtceu:raw_tantalite")
        .inputFluids("gtceu:drilling_fluid 500")
        .itemOutputs("1x gtceu:tantalite_ore")
        .duration(75)
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("wulfenite_ore_nether")
        .notConsumable("1x gtceu:raw_wulfenite")
        .itemOutputs("2x gtceu:wulfenite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("molybdenite_ore_nether")
        .notConsumable("1x gtceu:raw_molybdenite")
        .itemOutputs("1x gtceu:molybdenite_ore")
        .inputFluids("gtceu:drilling_fluid 500")
        .duration(75)
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("molybdenum_ore_nether_2") // Added a suffix
        .notConsumable("1x gtceu:raw_molybdenum")
        .itemOutputs("1x gtceu:molybdenum_ore")
        .inputFluids("gtceu:drilling_fluid 500")
        .duration(75)
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("powellite_ore_nether")
        .notConsumable("1x gtceu:raw_powellite")
        .itemOutputs("1x gtceu:powellite_ore")
        .inputFluids("gtceu:drilling_fluid 500")
        .duration(75)
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("goethite_ore_nether")
        .notConsumable("1x gtceu:raw_goethite")
        .itemOutputs("1x gtceu:goethite_ore")
        .inputFluids("gtceu:drilling_fluid 500")
        .duration(75)
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("yellow_limonite_ore_nether")
        .notConsumable("1x gtceu:raw_yellow_limonite")
        .itemOutputs("1x gtceu:yellow_limonite_ore")
        .duration(75)
        .EUt(512)
        .inputFluids("gtceu:drilling_fluid 500")
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("hematite_ore_nether")
        .notConsumable("1x gtceu:raw_hematite")
        .itemOutputs("1x gtceu:hematite_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("gold_ore_nether")
        .notConsumable("1x minecraft:raw_gold")
        .itemOutputs("1x minecraft:gold_ore")
        .inputFluids("gtceu:drilling_fluid 500")
        .duration(75)
        .EUt(512)
       .dimension("the_nether");
    gtr.dimensional_rift_extractor("quartzite_ore_nether")
        .notConsumable("1x gtceu:raw_quartzite")
        .itemOutputs("2x gtceu:quartzite_ore")
        .duration(75)
        .EUt(512)
        .inputFluids("gtceu:drilling_fluid 500")
        .dimension("the_nether");
    gtr.dimensional_rift_extractor("certus_quartz_ore_nether")
        .notConsumable("1x gtceu:raw_certus_quartz")
        .itemOutputs("1x gtceu:netherrack_certus_quartz_ore")
        .duration(75)
        .inputFluids("gtceu:drilling_fluid 500")
        .EUt(512)
        .dimension("the_nether");
      // End Recipes
      gtr.dimensional_rift_extractor("magnetite_ore_end")
      .notConsumable("9x gtceu:raw_magnetite")
      .inputFluids("gtceu:drilling_fluid 500")
      .itemOutputs("1x gtceu:magnetite_ore")
      .duration(75)
      .EUt(512)
      .dimension("the_end");
  gtr.dimensional_rift_extractor("bauxite_ore_end")
      .notConsumable("8x gtceu:raw_bauxite")
      .itemOutputs("2x gtceu:bauxite_ore")
      .inputFluids("gtceu:drilling_fluid 500")
      .duration(75)
      .EUt(512)
      .dimension("the_end");

  gtr.dimensional_rift_extractor("bornite_ore_end")
      .notConsumable("3x gtceu:raw_bornite")
      .itemOutputs("3x gtceu:bornite_ore")
      .duration(75)
      .inputFluids("gtceu:drilling_fluid 500")
      .EUt(512)
      .dimension("the_end");

  gtr.dimensional_rift_extractor("scheelite_ore_end")
      .notConsumable("6x gtceu:raw_scheelite")
      .itemOutputs("4x gtceu:scheelite_ore")
      .duration(75)
      .inputFluids("gtceu:drilling_fluid 500")
      .EUt(512)
      .dimension("the_end");

  gtr.dimensional_rift_extractor("pitchblende_ore_end")
      .notConsumable("9x gtceu:raw_pitchblende")
      .itemOutputs("5x gtceu:pitchblende_ore")
      .duration(75)
      .inputFluids("gtceu:drilling_fluid 500")
      .EUt(512)
      .dimension("the_end");

  gtr.dimensional_rift_extractor("naquadah_ore_end")
      .notConsumable("9x gtceu:raw_naquadah")
      .itemOutputs("6x gtceu:naquadah_ore")
      .duration(75)
      .inputFluids("gtceu:drilling_fluid 500")
      .EUt(512)
      .dimension("the_end");

});
