ServerEvents.recipes(event => {
    
    event.recipes.gtceu.large_chemical_reactor('oleum')
    .inputFluids('gtceu:sulfur_trioxide 244', 'gtceu:sulfuric_acid 1000')
    .outputFluids('gtceu:oleum 1000')
    .duration(134)
    .EUt(GTValues.VA[GTValues.IV]/2)
event.recipes.gtceu.large_chemical_reactor('concentrated_sulfuric_acid')
    .inputFluids('gtceu:oleum 300', 'minecraft:water 700')
    .outputFluids('gtceu:concentrated_sulfuric_acid 800')
    .duration(80)
    .EUt(GTValues.VA[GTValues.EV]/2)
event.recipes.gtceu.electrolyzer('concentrated_sulfuric_acid_to_hydrogen_peroxide')
    .inputFluids('gtceu:concentrated_sulfuric_acid 1000')
    .outputFluids('gtceu:hydrogen_peroxide 100', 'minecraft:water 300', 'gtceu:sulfuric_acid 500')
    .duration(550)
    .EUt(GTValues.VA[GTValues.IV]/2)
event.recipes.gtceu.large_chemical_reactor('acetone_cyanohydrin')
    .inputFluids('gtceu:acetone 1000', 'gtceu:hydrogen_cyanide 1000')
    .outputFluids('gtceu:acetone_cyanohydrin 1000')
    .duration(200)
    .EUt(GTValues.VA[GTValues.EV]/2)
event.recipes.gtceu.large_chemical_reactor('methyl_methacrylate')
    .inputFluids('gtceu:acetone_cyanohydrin 1000', 'gtceu:sulfuric_acid 1000', 'gtceu:methanol 750')
    .outputFluids('gtceu:methyl_methacrylate 1000', 'gtceu:ammonium_bisulfate_solution 1000')
    .duration(300)
    .EUt(GTValues.VA[GTValues.IV]/2)
event.recipes.gtceu.distillation_tower('ammonium_bisulfate_solution_to_dust')
    .inputFluids('gtceu:ammonium_bisulfate_solution 1000')
    .outputFluids('gtceu:sulfuric_acid 500', 'minecraft:water 600', 'gtceu:ammonia 120')
    .itemOutputs('12x gtceu:ammonium_bisulfate_dust')
    .duration(240)
    .EUt(GTValues.VA[GTValues.EV]/2)
    event.recipes.gtceu.electrolyzer('ammonium_bisulfate_dust_to_ammonium_persulfate')
    .itemInputs('7x gtceu:ammonium_bisulfate_dust')
    .outputFluids('gtceu:hydrogen 1000', 'gtceu:ammonium_persulfate 250')
    .duration(130)
    .EUt(GTValues.VA[GTValues.IV]/2)
    event.recipes.gtceu.large_chemical_reactor('advanced_pmma_polymerization') 
    .inputFluids([
        'gtceu:methyl_methacrylate 144',    
        'gtceu:ammonium_persulfate 750',     
        'gtceu:hydrogen_peroxide 250'         
    ])
    .outputFluids('gtceu:polymethyl_methacrylate 216')
    .duration(800) 
     .EUt(GTValues.VA[GTValues.IV]/2)
     event.recipes.gtceu.large_chemical_reactor('ammonium_bisulfate_solution') 
    .inputFluids([
        'gtceu:sulfuric_acid 200',    
        'gtceu:ammonia 750',              
    ])
    .outputFluids("gtceu:ammonium_bisulfate_solution 250")
    .duration(60) 
     .EUt(GTValues.VA[GTValues.IV]/2)

})