ServerEvents.recipes(event => {


        event.recipes.gtceu.ember_igniter('flaming_dust')
        .itemInputs('2x gtceu:dormant_ember_dust', '1x gtceu:magma_dust')
        .inputFluids('minecraft:lava 1')
        .itemOutputs('1x kubejs:flaming_dust')
        .duration(150)
        .EUt(20)
        event.recipes.gtceu.alloy_smelter('flamingmatrix')
        .itemInputs('1x kubejs:flaming_dust', '1x minecraft:clay_ball')
        .itemOutputs('4x hostilenetworks:prediction_matrix')
        .duration(100)
        .EUt(32)
        event.recipes.gtceu.assembler('lv_machine_casing')
        .circuit(8)
        .itemInputs('8x gtceu:aurum_steel_plate')
        .itemOutputs('1x gtceu:lv_machine_casing')
        .duration(50)
        .EUt(32)
        event.recipes.gtceu.macerator('magma_dust')
        .itemInputs('1x minecraft:magma_block')
        .itemOutputs('1x gtceu:magma_dust')
        .duration(50)
        .EUt(32)
        event.recipes.gtceu.assembler('steam_machine_casing')
        .circuit(6)
        .itemInputs('6x gtceu:fiery_bronze_plate', '1x minecraft:bricks')
        .itemOutputs('1x gtceu:steam_machine_casing')
        .duration(50)
        .EUt(32)
})
