
GTCEuStartupEvents.registry('gtceu:recipe_type', phoenixvine => {
    phoenixvine.create('pressurized_fission_reactor')
        .category('fission')
        .setEUIO('out')
        .setMaxIOSize(1, 1, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC);
        phoenixvine.create('advanced_pressurized_fission_reactor')
        .category('fission')
        .setMaxIOSize(1, 1, 1, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC);
        phoenixvine.create('heat_exchanging')
        .category('fission')
        .setEUIO('out')
        .setMaxIOSize(0, 0, 1, 1)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL);
          phoenixvine.create('high_performace_breeder_reactor')
        .category('fission')
        .setEUIO('out')
        .setMaxIOSize(2, 2, 2, 2)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.CHEMICAL);
});

GTCEuStartupEvents.registry('gtceu:machine', phoenixvine => {
    phoenixvine.create('heat_exchanger', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('heat_exchanging')
        .generator(true)
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock("kubejs:fissile_heat_safe_casing"))
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("BBBBBBB", "BCCCCCB", "BCCCCCB", "BCCCCCB", "BBBBBBB")
        .aisle("BBBBBBB", "BAAAAAB", "BAAEAAB", "BAAAAAB", "BBCBCBB")
        .aisle("BBBBBBB", "BAEAEAB", "BEEEEEB", "BAEAEAB", "BCCBCCB")
        .aisle("BBBBBBB", "BAAAAAB", "BAAEAAB", "BAAAAAB", "BBCBCBB")
        .aisle("BBBBBBB", "BCCCCCB", "BCCDCCB", "BCCCCCB", "BBBBBBB")
           .where("A", Predicates.blocks("minecraft:air"))
           .where("B", Predicates.blocks("kubejs:fissile_reaction_safe_casing"))
           .where('C', Predicates.blocks('kubejs:fissile_heat_safe_casing').setMinGlobalLimited(6) // Corrected line
           .or(Predicates.autoAbilities(definition.getRecipeTypes()))
           .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
           .where('D', Predicates.controller(Predicates.blocks(definition.get())))
           .where("E", Predicates.blocks("kubejs:fissile_safe_gearbox"))
            .build())
        .workableCasingModel(
          "kubejs:block/fissile_heat_safe_casing",
            "gtceu:block/multiblock/large_chemical_reactor"
        )
    phoenixvine.create('pressurized_fission_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('pressurized_fission_reactor')
        .generator(true)
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock("kubejs:fissile_reaction_safe_casing"))
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("BCCCB", "CDDDC", "CDDDC", "CDDDC", "BCCCB")
        .aisle("CEFEC", "DGGGD", "DGGGD", "DGGGD", "CDHDC")
        .aisle("CFEFC", "DGFGD", "DGFGD", "DGFGD", "CHEHC")
        .aisle("CEFEC", "DGGGD", "DGGGD", "DGGGD", "CDHDC")
        .aisle("BCICB", "CDDDC", "CDDDC", "CDDDC", "BCCCB")
        .where("A", Predicates.blocks("minecraft:air"))
        .where('B', Predicates.any())
        .where('C', Predicates.blocks('kubejs:fissile_reaction_safe_casing').setMinGlobalLimited(12) // Corrected line
       .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
        .where("D", Predicates.blocks("minecraft:tinted_glass"))
        .where("E", Predicates.blocks("gtceu:kanthal_coil_block"))
        .where("F", Predicates.blocks("kubejs:base_fission_casing"))
        .where("G", Predicates.blocks("minecraft:ice"))
        .where("H", Predicates.blocks("kubejs:fissile_heat_safe_casing"))
        .where('I', Predicates.controller(Predicates.blocks(definition.get())))
            .build())
        .workableCasingModel(
          "kubejs:block/fissile_reaction_safe_casing",
            "gtceu:block/multiblock/fusion_reactor"
        )
        phoenixvine.create('advanced_pressurized_fission_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('advanced_pressurized_fission_reactor')
        .recipeModifiers([GTRecipeModifiers.OC_NON_PERFECT, GTRecipeModifiers.BATCH_MODE])
        .appearanceBlock(() => Block.getBlock("kubejs:fissile_reaction_safe_casing"))
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("BCCCCCB", "CDDDDDC", "CDDDDDC", "CDDDDDC", "CDDDDDC", "CDDDDDC", "BCCCCCB")
        .aisle("CCCCCCC", "DAAEAAD", "DAAEAAD", "DAAEAAD", "DAAEAAD", "DAAEAAD", "CDDFDDC")
        .aisle("CCGEGCC", "DAHHHAD", "DAHHHAD", "DAHHHAD", "DAIIIAD", "DAEEEAD", "CDFGFDC")
        .aisle("CCEEECC", "DEHEHED", "DEHEHED", "DEHEHED", "DEIEIED", "DEEEEED", "CFGFGFC")
        .aisle("CCGEGCC", "DAHHHAD", "DAHHHAD", "DAHHHAD", "DAIIIAD", "DAEEEAD", "CDFGFDC")
        .aisle("CCCCCCC", "DAAEAAD", "DAAEAAD", "DAAEAAD", "DAAEAAD", "DAAEAAD", "CDDFDDC")
        .aisle("BCCJCCB", "CDDDDDC", "CDDDDDC", "CDDDDDC", "CDDDDDC", "CDDDDDC", "BCCCCCB")
           .where("A", Predicates.blocks("minecraft:air"))
           .where('B', Predicates.any())
           .where('C', Predicates.blocks('kubejs:fissile_reaction_safe_casing').setMinGlobalLimited(12) // Corrected line
         .or(Predicates.autoAbilities(definition.getRecipeTypes()))
        .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1)))
           .where("D", Predicates.blocks("minecraft:tinted_glass"))
           .where("E", Predicates.blocks("kubejs:base_fission_casing"))
           .where("F", Predicates.blocks("kubejs:fissile_heat_safe_casing"))
           .where("G", Predicates.blocks("gtceu:nichrome_coil_block"))
           .where("H", Predicates.blocks("kubejs:fission_cooling_casing"))
           .where("I", Predicates.blocks("minecraft:ice"))
           .where('J', Predicates.controller(Predicates.blocks(definition.get())))
            .build())
        .workableCasingModel(
          "kubejs:block/fissile_reaction_safe_casing",
            "gtceu:block/multiblock/fusion_reactor"
        )
             phoenixvine.create('high_performace_breeder_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('high_performace_breeder_reactor')
        .generator(true)
        .noRecipeModifier()
        .appearanceBlock(() => Block.getBlock("kubejs:fissile_reaction_safe_casing"))
        .pattern(definition => FactoryBlockPattern.start()
       .aisle("BBCCCCCBB", "BBDEEEDBB", "BBDEEEDBB", "BBDEEEDBB", "BBDFFFDBB", "BBDFFFDBB", "BBCFFFCBB", "BBCFFFCBB", "BBBBBBBBB")
.aisle("BCCCCCCCB", "BGAAAAHGB", "BGAAAAHGB", "BGAAAAHGB", "BGAAAAHGB", "BGAAAAHGB", "BCAAAAHCB", "BCAAAAHCB", "BBCCCCCBB")
.aisle("CCCCCCCCC", "DHIAAAIHD", "DHIAAAIHD", "DHIAAAIHD", "DHIAAAIHD", "DHIJJJIHD", "CHIKKKIHC", "CHIAAAIHC", "BCCCCCCCB")
.aisle("CCCCCCCCC", "EAALILAAE", "EAALILAAE", "EAALILAAE", "FAALILAAF", "FAJJIJJAF", "FAKKIKKAF", "FAAAIAAAF", "BCCGGGCCB")
.aisle("CCCCCCCCC", "EAAIJIAAE", "EAAIJIAAE", "EAAIJIAAE", "FAAIJIAAF", "FAJIJIJAF", "FAKIDIKAF", "FAAIDIAAF", "BCCGJGCCB")
.aisle("CCCCCCCCC", "EAALILAAE", "EAALILAAE", "EAALILAAE", "FAALILAAF", "FAJJIJJAF", "FAKKIKKAF", "FAAAIAAAF", "BCCGGGCCB")
.aisle("CCCCCCCCC", "DHIAAAIHD", "DHIAAAIHD", "DHIAAAIHD", "DHIAAAIHD", "DHIJJJIHD", "CHIKKKIHC", "CHIAAAIHC", "BCCCCCCCB")
.aisle("BCCCCCCCB", "BGHAAAHGB", "BGHAAAHGB", "BGHAAAHGB", "BGHAAAHGB", "BGHAAAHGB", "BCHAAAHCB", "BCHAAAHCB", "BBCCCCCBB")
.aisle("BBCCMCCBB", "BBDEEEDBB", "BBDEEEDBB", "BBDEEEDBB", "BBDFFFDBB", "BBDFFFDBB", "BBCFFFCBB", "BBCFFFCBB", "BBBBBBBBB")
   .where("A", Predicates.blocks("minecraft:air"))
   .where('B', Predicates.any())
   .where("C", 
      Predicates.blocks("kubejs:fissile_reaction_safe_casing").setMinGlobalLimited(10)
         .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1))
           .or(Predicates.abilities(PartAbility.SUBSTATION_OUTPUT_ENERGY).setMaxGlobalLimited(2))
         .or(Predicates.autoAbilities(definition.getRecipeTypes()))
   )
   .where("D", Predicates.blocks("kubejs:fissile_heat_safe_casing"))
   .where("E", Predicates.blocks("minecraft:tinted_glass"))
   .where("F", Predicates.blocks("gtceu:high_temperature_smelting_casing"))
   .where("G", Predicates.blocks("gtceu:heat_vent"))
   .where("H", Predicates.blocks("gtceu:ptfe_pipe_casing"))
   .where("I", Predicates.blocks("kubejs:base_fission_casing"))
   .where("J", Predicates.blocks("gtceu:hssg_coil_block"))
   .where("K", Predicates.blocks("kubejs:fission_cooling_casing"))
   .where("L", Predicates.blocks("gtceu:tungstensteel_pipe_casing"))
   .where('M', Predicates.controller(Predicates.blocks(definition.get())))
   .build()
)
.workableCasingModel(
  "kubejs:block/fissile_reaction_safe_casing",
    "gtceu:block/multiblock/fusion_reactor"
);
});
