GTCEuStartupEvents.registry('gtceu:recipe_type', phoenixvine => {
    phoenixvine.create('melferious_matrix')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(4, 4, 0, 0)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC);
});

GTCEuStartupEvents.registry('gtceu:machine', phoenixvine => {
    phoenixvine.create('melferious_matrix', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('melferious_matrix')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING)
        .pattern(definition => FactoryBlockPattern.start()
        .aisle("AAABBBAAA", "AAABBBAAA", "AAACCCAAA", "AAACCCAAA", "AAADDDAAA", "AAAAAAAAA")
.aisle("ABBBBBBBA", "ABEFFFEBA", "ACCFFFCCA", "ACCFFFCCA", "ADDFFFDDA", "AADDDDDAA")
.aisle("BBBBBBBBB", "BGFHHHFGB", "CGFIIIFGC", "CHFAAAFHC", "ADFAAAFDA", "AADAFADAA")
.aisle("BBBBBBBBB", "BGFHJHFGB", "CGFIKIFGC", "CHFALAFHC", "ADFAMAFDA", "AADFFFDAA")
.aisle("BBBBBBBBB", "BGFHHHFGB", "CGFIIIFGC", "CHFAAAFHC", "ADFAAAFDA", "AADAFADAA")
.aisle("ABBBBBBBA", "ABEFFFEBA", "ACCFFFCCA", "ACCFFFCCA", "ADDFFFDDA", "AADDDDDAA")
.aisle("AAABBBAAA", "AAAB@BAAA", "AAACCCAAA", "AAACCCAAA", "AAADDDAAA", "AAAAAAAAA")
   .where("A", Predicates.blocks("minecraft:air"))
   .where("@", Predicates.controller(Predicates.blocks(definition.get())))
   .where("B", Predicates.blocks("gtceu:sturdy_machine_casing"))
   .where("C", Predicates.blocks("gtceu:tungsten_steel_frame"))
   .where("D", Predicates.blocks("minecraft:warped_hyphae"))
   .where("E", Predicates.blocks("gtceu:tungsten_steel_crate"))
   .where("F", Predicates.blocks("gtceu:treated_wood_frame"))
   .where("G", Predicates.blocks("productivebees:advanced_oak_beehive"))
   .where("H", Predicates.blocks("minecraft:honeycomb_block"))
   .where("I", Predicates.blocks("minecraft:honey_block"))
   .where("J", Predicates.blocks("productivebees:breeding_chamber"))
   .where("K", Predicates.blocks("productivebees:incubator"))
   .where("L", Predicates.blocks("minecraft:dirt"))
   .where("M", Predicates.blocks("minecraft:poppy"))
            .build())
            .workableCasingRenderer('gtceu:block/casings/solid/machine_casing_sturdy_hsse', 'gtceu:block/multiblock/implosion_compressor', false)
});
// .setMinGlobalLimited(10) // Corrected line
     //           .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1))
       //         .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
      //          .or(Predicates.abilities(PartAbility.INPUT_LASER).setMaxGlobalLimited(1))
        //        .or(Predicates.autoAbilities(definition.getRecipeTypes())))