GTCEuStartupEvents.registry('gtceu:recipe_type', phoenixvine => {
    phoenixvine.create('melferious_matrix')
        .category('multiblock')
        .setEUIO('in')
        .setMaxIOSize(4, 4, 4, 6)
        .setSlotOverlay(false, false, GuiTextures.SOLIDIFIER_OVERLAY)
        .setProgressBar(GuiTextures.PROGRESS_BAR_ARROW, FillDirection.LEFT_TO_RIGHT)
        .setSound(GTSoundEntries.ARC);
});

GTCEuStartupEvents.registry('gtceu:machine', phoenixvine => {
    phoenixvine.create('melferious_matrix', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeTypes('melferious_matrix')
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.OC_PERFECT_SUBTICK])
        .appearanceBlock(GCYMBlocks.CASING_HIGH_TEMPERATURE_SMELTING)
        .pattern(definition => FactoryBlockPattern.start()
.aisle("BBBCCCBBB", "BBBCCCBBB", "BBBDDDBBB", "BBBDDDBBB", "BBBEEEBBB", "BBBBBBBBB")
.aisle("BCCCCCCCB", "BCFGGGFCB", "BDDGGGDDB", "BDDGGGDDB", "BEEGGGEEB", "BBEEEEEBB")
.aisle("CCCCCCCCC", "CHGIIIGHC", "DHGJJJGHD", "DIGAAAGID", "BEGAAAGEB", "BBEAGAEBB")
.aisle("CCCCCCCCC", "CHGIKIGHC", "DHGJLJGHD", "DIGA1AGID", "BEGAMAGEB", "BBEGGGEBB")
.aisle("CCCCCCCCC", "CHGIIIGHC", "DHGJJJGHD", "DIGAAAGID", "BEGAAAGEB", "BBEAGAEBB")
.aisle("BCCCCCCCB", "BCFGGGFCB", "BDDGGGDDB", "BDDGGGDDB", "BEEGGGEEB", "BBEEEEEBB")
.aisle("BBBCCCBBB", "BBBCNCBBB", "BBBDDDBBB", "BBBDDDBBB", "BBBEEEBBB", "BBBBBBBBB")
   .where("A", Predicates.blocks("minecraft:air"))
   .where('B', Predicates.any())
   .where("1", Predicates.blocks("minecraft:dirt"))
   .where("C", Predicates.blocks("gtceu:sturdy_machine_casing").setMinGlobalLimited(10)
   .or(Predicates.abilities(PartAbility.MAINTENANCE).setMaxGlobalLimited(1))
   .or(Predicates.abilities(PartAbility.PARALLEL_HATCH).setMaxGlobalLimited(1))
   .or(Predicates.autoAbilities(definition.getRecipeTypes())))
   .where("D", Predicates.blocks("gtceu:tungsten_steel_frame"))
   .where("E", Predicates.blocks("minecraft:warped_hyphae"))
   .where("F", Predicates.blocks("gtceu:tungsten_steel_crate"))
   .where("G", Predicates.blocks("gtceu:treated_wood_frame"))
   .where("H", Predicates.blocks("productivebees:advanced_oak_beehive"))
   .where("I", Predicates.blocks("minecraft:honeycomb_block"))
   .where("J", Predicates.blocks("minecraft:honey_block"))
   .where("K", Predicates.blocks("productivebees:breeding_chamber"))
   .where("L", Predicates.blocks("productivebees:incubator"))
   .where("M", Predicates.blocks("minecraft:poppy"))
   .where("N", Predicates.controller(Predicates.blocks(definition.get())))
            .build())
            .workableCasingRenderer('gtceu:block/casings/solid/machine_casing_sturdy_hsse', 'gtceu:block/multiblock/implosion_compressor', false)
});
